# Generated by Django 2.2.19 on 2021-03-01 01:51

import OnlineExamination.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMentor',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=20, unique=True)),
                ('LastName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the define format', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=1234, max_length=20)),
                ('national_ID', models.CharField(max_length=20, null=True, unique=True)),
                ('national_ID_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=OnlineExamination.models.upload_image, width_field='width_field')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='exams',
            name='time_duration',
        ),
        migrations.AddField(
            model_name='exams',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limitation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='national_ID',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('lower6', 'Lower 6'), ('upper6', 'Upper 6'), ('professional', 'Professional')], max_length=20, null=True),
        ),
    ]
