# Generated by Django 2.2.19 on 2021-03-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0002_auto_20210301_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyMentor',
        ),
    ]
