# Generated by Django 2.2.19 on 2021-03-01 02:02

import OnlineExamination.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0003_delete_studymentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMentor',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=20, unique=True)),
                ('LastName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the define format', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=1234, max_length=20)),
                ('national_ID', models.CharField(max_length=20, null=True, unique=True)),
                ('national_ID_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=OnlineExamination.models.upload_image, width_field='width_field')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
    ]
