# Generated by Django 2.2.19 on 2021-03-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0004_studymentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.StudyMentor'),
        ),
        migrations.AddField(
            model_name='studymentor',
            name='idmentor',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studymentor',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
