# Generated by Django 2.2.19 on 2021-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0005_auto_20210301_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymentor',
            name='idmentor',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
