# Generated by Django 2.2.19 on 2021-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0006_auto_20210301_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymentor',
            name='idmentor',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
