# Generated by Django 2.2.19 on 2021-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0007_auto_20210301_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('idstaff', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=20, unique=True)),
                ('FirstName', models.CharField(max_length=20, unique=True)),
                ('LastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=1234, max_length=20)),
            ],
        ),
    ]
