# Generated by Django 2.2.19 on 2021-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0008_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
