# Generated by Django 2.2.19 on 2021-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0011_remove_studymentor_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymentor',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
