# Generated by Django 2.2.19 on 2021-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='national_ID',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('lower6', 'Lower 6'), ('upper6', 'Upper 6'), ('professional', 'Professional')], max_length=20, null=True),
        ),
    ]
