# Generated by Django 2.2.19 on 2021-02-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0002_auto_20210227_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limitation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
