# Generated by Django 2.2.19 on 2021-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0003_auto_20210227_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='time_duration',
        ),
        migrations.AddField(
            model_name='exams',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
