# Generated by Django 2.2.19 on 2021-02-27 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0004_auto_20210227_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMentor',
            fields=[
                ('FirstName', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('LastName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the define format', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('national_ID', models.CharField(max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
    ]
