# Generated by Django 2.2.19 on 2021-02-27 14:10

import OnlineExamination.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0005_studymentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymentor',
            name='national_ID_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=OnlineExamination.models.upload_image, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='studymentor',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Student'),
        ),
    ]
