# Generated by Django 2.2.19 on 2021-02-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0006_auto_20210227_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymentor',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.StudyMentor'),
        ),
    ]
