# Generated by Django 2.2.19 on 2021-02-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0007_auto_20210227_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymentor',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Student'),
        ),
    ]
