# Generated by Django 2.2.19 on 2021-02-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0008_studymentor_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymentor',
            name='students',
        ),
    ]
