# Generated by Django 2.2.19 on 2021-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0009_remove_studymentor_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymentor',
            name='password',
            field=models.CharField(default=1234, max_length=20),
        ),
    ]
