# Generated by Django 2.2.19 on 2021-03-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0010_studymentor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymentor',
            name='user',
            field=models.CharField(default='test', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studymentor',
            name='FirstName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
